Repository KU-Solution-Challenge-GoGreen/GoGreen-Server, pull requests merged in 2023-03, with the labels that each got.

#9 [Feat] Firebase init 개선 & Auth 관련 타이핑 및 로직 개선
  src/app/app.controller.ts
  src/auth/auth.guard.ts
  src/auth/decorator/user.decorator.ts
  src/auth/firebase/firebase.module.ts
  src/auth/firebase/firebase.service.ts
  src/auth/firebase/interface/firebase-admin.interface.ts
  src/auth/type/request-with-auth.ts
  src/auth/type/user-info.type.ts
Labels: feat

#10 [Feat] 회원가입 & 닉네임 중복확인 API
  src/app/app.controller.ts
  src/app/app.module.ts
  src/auth/auth.controller.spec.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.repository.ts
  src/auth/auth.service.spec.ts
  src/auth/auth.service.ts
  src/auth/decorator/user.decorator.ts
  src/auth/dto/check-duplicate.dto.ts
  src/auth/dto/user-info.dto.ts
  src/auth/guard/auth.guard.ts
  src/auth/payload/register.payload.ts
  src/auth/type/register-data.type.ts
  src/auth/type/request-with.auth.type.ts
  src/auth/type/user-info-with-type.type.ts
Labels: feat

#15 [Fix] 사용하지 않는 api 제거 & docs 개선
  src/app/app.controller.spec.ts
  src/app/app.controller.ts
  src/app/app.module.ts
  src/app/app.service.ts
  src/auth/auth.controller.spec.ts
  src/auth/auth.controller.ts
  src/auth/auth.service.spec.ts
Labels: bug

#12 [Infra] CI 파이프라인 추가
  .github/workflows/CI.yml
  package-lock.json
  package.json
  src/common/common.module.ts
  src/common/services/prisma.service.ts
  yarn.lock
Labels: infra

#19 [Feat] 회원가입 로직 & Guard 에서 vegan type 삭제
  .github/PULL_REQUEST_TEMPLATE.md
  src/auth/auth.repository.ts
  src/auth/auth.service.ts
  src/auth/dto/user-info.dto.ts
  src/auth/guard/auth.guard.ts
  src/auth/payload/register.payload.ts
  src/auth/type/register-data.type.ts
  src/auth/type/user-info-with-type.type.ts
  src/auth/type/user-info.type.ts
Labels: feat

#23 [Schema] recipe에서 type id 제외
  prisma/migrations/20230307042159_remove_type_id_from_recipe/migration.sql
  prisma/schema.prisma
Labels: schema

#20 [Feat] Ingredient Module 추가
  src/app/app.module.ts
  src/common/dto/bulk-create.dto.ts
  src/ingredient/dto/category-with-ingredient-list.dto.ts
  src/ingredient/dto/ingredient-with-category.dto.ts
  src/ingredient/ingredient.controller.ts
  src/ingredient/ingredient.module.ts
  src/ingredient/ingredient.repository.ts
  src/ingredient/ingredient.service.ts
  src/ingredient/payload/ingredient-bulk-create.payload.ts
  src/ingredient/type/category-with-ingredient-list.type.ts
  src/ingredient/type/ingredient-create-input.type.ts
  src/ingredient/type/ingredient-with-category.type.ts
Labels: feat

#29 [Feat] Recipe 생성 API
  src/app/app.module.ts
  src/auth/auth.repository.ts
  src/auth/auth.service.ts
  src/auth/decorator/user.decorator.ts
  src/auth/dto/user-info.dto.ts
  src/auth/firebase/firebase.module.ts
  src/auth/guard/auth.guard.ts
  src/auth/type/request-with.auth.type.ts
  src/auth/type/user-data.type.ts
  src/auth/type/user-info-with-type.type.ts
  src/main.ts
  src/recipe/dto/create-recipe.dto.ts
  src/recipe/dto/recipe-step.dto.ts
  src/recipe/payload/create-recipe-step.payload.ts
  src/recipe/payload/create-recipe.payload.ts
  src/recipe/recipe.controller.ts
  src/recipe/recipe.module.ts
  src/recipe/recipe.repository.ts
  src/recipe/recipe.service.ts
  src/recipe/type/recipe-create-input.type.ts
  src/recipe/type/recipe-with-step.type.ts
Labels: feat

#30 [Infra] development CD 워크플로우
  .github/workflows/CD-devlopment.yml
  dev.dockerfile
  src/app/app.controller.ts
Labels: infra

#31 [Feat] Recipe bookmark API
  src/recipe/dto/recipe-bookmark.dto.ts
  src/recipe/recipe.controller.ts
  src/recipe/recipe.repository.ts
  src/recipe/recipe.service.ts
Labels: feat

#41 [Feat] Meal module 생성
  src/app/app.module.ts
  src/meal/meal.controller.ts
  src/meal/meal.module.ts
  src/meal/meal.repository.ts
  src/meal/meal.service.ts
Labels: feat

#42 [Feat] Recipe Summary 조회 API
  src/recipe/dto/recipe-summary.dto.ts
  src/recipe/recipe.controller.ts
  src/recipe/recipe.repository.ts
  src/recipe/recipe.service.ts
  src/recipe/type/recipe-summary.type.ts
Labels: feat

#43 [Feat] Meal 생성 API
  src/meal/dto/meal.dto.ts
  src/meal/meal.controller.ts
  src/meal/meal.repository.ts
  src/meal/meal.service.ts
  src/meal/payload/create-meal.payload.ts
  src/meal/type/create-meal-input.type.ts
  src/meal/type/meal.type.ts
Labels: feat

#46 [Feat] 날짜별 Meal 조회 API
  src/common/query/date.query.ts
  src/meal/meal.controller.ts
  src/meal/meal.repository.ts
  src/meal/meal.service.ts
Labels: feat

#45 [Feat] Meal 검색 API
  src/common/query/date.query.ts
  src/meal/dto/meal-summary.dto.ts
  src/meal/meal.controller.ts
  src/meal/meal.repository.ts
  src/meal/meal.service.ts
  src/meal/query/search-meal.query.ts
  src/meal/type/meal-summary.type.ts
Labels: feat

#50 [Feat] Login API
  src/auth/auth.controller.ts
Labels: feat

#51 [Feat/Schema] meal table 인덱스 추가 & time to date
  prisma/migrations/20230317024215_add_index_to_meal_table_and_change_time_to_date/migration.sql
  prisma/schema.prisma
  src/meal/dto/meal-summary.dto.ts
  src/meal/dto/meal.dto.ts
  src/meal/dto/mealId-dto.ts
  src/meal/meal.repository.ts
  src/meal/meal.service.ts
  src/meal/payload/create-meal.payload.ts
  src/meal/type/create-meal-input.type.ts
  src/meal/type/meal-summary.type.ts
  src/meal/type/meal.type.ts
Labels: feat, schema

#55 [Fix] 썸네일 사진 선택 로직 수정
  src/meal/meal.repository.ts
  src/meal/meal.service.ts
  src/recipe/recipe.controller.ts
  src/recipe/recipe.repository.ts
  src/recipe/recipe.service.ts
Labels: bug

#47 [Feat] User Update API
  src/app/app.module.ts
  src/user/dto/user.dto.ts
  src/user/payload/user.payload.ts
  src/user/user.controller.ts
  src/user/user.module.ts
  src/user/user.repository.ts
  src/user/user.service.ts
Labels: feat

#60 [Fix] UserInfoDto 중복선언 문제
  src/auth/auth.controller.ts
  src/auth/dto/user-info.dto.ts
  src/user/dto/user-detail.dto.ts
  src/user/dto/user.dto.ts
  src/user/user.controller.ts
  src/user/user.service.ts
Labels: bug

#64 [Fix] Docs와 실제 DTO의 차이 fix
  src/meal/dto/meal.dto.ts
  src/meal/payload/meal.payload.ts
  src/meal/query/search-meal.query.ts
  src/user/payload/user.payload.ts
Labels: bug

#65 [Schema] Meal의 description 이름을 memo로 변경
  prisma/migrations/20230324083617_change_meal_description_to_memo/migration.sql
  prisma/schema.prisma
  src/meal/dto/meal-summary.dto.ts
  src/meal/dto/meal.dto.ts
  src/meal/meal.repository.ts
  src/meal/meal.service.ts
  src/meal/payload/meal.payload.ts
  src/meal/type/create-meal-input.type.ts
  src/meal/type/meal-summary.type.ts
  src/meal/type/meal.type.ts
  src/meal/type/update-meal-input.type.ts
Labels: schema

#66 Get Ingredients API
  src/ingredient/dto/ingredient-list.dto.ts
  src/ingredient/ingredient.controller.ts
  src/ingredient/ingredient.repository.ts
  src/ingredient/ingredient.service.ts
  src/ingredient/type/category-with-ingredient-list.type.ts
  src/ingredient/type/ingredient.type.ts
Labels: feat

#68 [Fix] 유저 수정 로직 개선 & meal 검색 시 쿼리가 없는 경우 대응
  src/meal/dto/meal-summary.dto.ts
  src/meal/meal.repository.ts
  src/meal/meal.service.ts
  src/meal/query/search-meal.query.ts
  src/user/user.repository.ts
  src/user/user.service.ts
Labels: bug

#72 [Feat] MealSummaryDto에 username 추가
  src/meal/dto/meal-summary.dto.ts
  src/meal/meal.repository.ts
  src/meal/type/meal-summary.type.ts
Labels: feat

#74 [Fix] avgFootprint가 meal이 0개일 때 null로 내려가던 현상 수정
  src/user/user.service.ts
Labels: bug
